### ISSUE TITLE
Textarea missing red border for validation errors

### ISSUE THREAD

**Issue by egze** [fluxonui/fluxon#10]
### Fluxon UI Version

1.0.11

### Phoenix LiveView Version

1.0.1

### Current Behavior

Textarea is not getting the red border if it has errors.

<img width="615" alt="image" src="https://github.com/user-attachments/assets/c957821d-ca34-4efe-9aca-d4bd6fe0eb16" />

What is also odd, when I click the textarea - it then shows the red border together with the blue focus border.

### Expected Behavior

Should be consistent with other form inputs.

### Browser

Safari

### Verification

- [X] I have searched for existing issues and confirmed this is not a duplicate
- [X] I have tested this issue with the latest version of Fluxon UI
- [X] I have included all the information needed to reproduce this issue

**Comment by andrielfn** [comment]
Fixed and scheduled for the next release! Thank you for reporting.

**Comment by andrielfn** [comment]
v1.0.12 published with the fix.

**Comment by andrielfn** [comment]
v1.0.12 published with the fix.
