### ISSUE TITLE
Select stealing focus from input fields when clicked outside

### ISSUE THREAD

**Issue by egze** [fluxonui/fluxon#11]
### Fluxon UI Version

1.0.11

### Phoenix LiveView Version

1.0.1

### Current Behavior

This is a tricky one 😄 

I have a select opened, then I click inside another input field. What happens is: I see the input focused for a split second, but then the select hook is processing the click-outside for the select (at least that's what imagine it does), and it steals the focus from the input field.

https://github.com/user-attachments/assets/ad784237-6244-4b6f-b503-779818c10c48

### Expected Behavior

The focus should stay in the clicked input field.

### Browser

Safari

### Verification

- [X] I have searched for existing issues and confirmed this is not a duplicate
- [X] I have tested this issue with the latest version of Fluxon UI
- [X] I have included all the information needed to reproduce this issue

**Comment by egze** [comment]
Please also see inconsistencies with the red border when clicking on the non-native select.


https://github.com/user-attachments/assets/0ebd79d6-94ee-4e30-a2e5-7286bb03904f

**Comment by andrielfn** [comment]
I won't lie, I did this on purpose last week while trying to mimic the native select as closely as possible. When we open a native select and click outside it remains focused, then it lose focus only on the second click. 

But thinking a bit more about it now, I agree that it's not a very good idea, as it creates more confusion and issues than benefits.

I will 'revert' it back to lose focus (and obviously close the list box) on the click outside.

**Comment by andrielfn** [comment]
A quick comparison with the native select:

https://github.com/user-attachments/assets/b2b6117f-78c7-4734-b140-3b6d7738c7db

Tbh, my natural expectation is that it should indeed immediately focus on the next element instead of just closing the list box first. A11y is hard 😄

**Comment by egze** [comment]
Interesting. I guess what the native select does differently is - the other field never receives focus on the first click.

**Comment by andrielfn** [comment]
v1.0.12 published with the fix.
