### ISSUE TITLE
Website UI issue (I assume you are using fluxon there)

### ISSUE THREAD

**Issue by garlandcrow** [fluxonui/fluxon#3]
### Fluxon UI Version

Your website

### Phoenix LiveView Version

Your website

### Current Behavior

The icons in the navbar on fluxonui.com are rendered small (for dark light toggle) or squished (for the avatar intials). 
![IMG_2793](https://github.com/user-attachments/assets/24fad11b-0174-4ba9-ad16-c8a7929e27e3)

### Expected Behavior

I would assume icons would be the same size as the hamburger menu. 

### Browser

Safari

### Verification

- [ ] I have searched for existing issues and confirmed this is not a duplicate
- [ ] I have tested this issue with the latest version of Fluxon UI
- [X] I have included all the information needed to reproduce this issue

**Comment by andrielfn** [comment]
Hey @garlandcrow, thanks for the report. That's definitely too many items in the header for small devices, and that hamburger button shouldn't be there. Good catch.

Already fixed and deployed!
