### ISSUE TITLE
Wrong path in installation docs for JS resources

### ISSUE THREAD

**Issue by kevinschweikert** [fluxonui/fluxon#6]
### Fluxon UI Version

1.0.9

### Phoenix LiveView Version

1.0.1

### Current Behavior

The current docs say, to change the `app.js` to the follwing. But the path to `fluxon` is not in the node_modules folder but in the deps folder

```diff
import 'phoenix_html';
import { Socket } from 'phoenix';
import { LiveSocket } from 'phoenix_live_view';
+import { Hooks as FluxonHooks, DOM as FluxonDOM } from 'fluxon';

let liveSocket = new LiveSocket("/live", Socket, {
+  hooks: {...Hooks, ...FluxonHooks},
  dom: {
    onBeforeElUpdated(from, to) {
+      FluxonDOM.onBeforeElUpdated(from, to);
    },
  },
});
```

### Reproduction Steps

Follow installation docs

### Expected Behavior

```diff
import 'phoenix_html';
import { Socket } from 'phoenix';
import { LiveSocket } from 'phoenix_live_view';
-import { Hooks as FluxonHooks, DOM as FluxonDOM } from 'fluxon'; 
+import { Hooks as FluxonHooks, DOM as FluxonDOM } from "../../deps/fluxon";

let liveSocket = new LiveSocket("/live", Socket, {
  hooks: {...Hooks, ...FluxonHooks}, // [!code ++]
  dom: {
    onBeforeElUpdated(from, to) {
      FluxonDOM.onBeforeElUpdated(from, to); // [!code ++]
    },
  },
});
```

### Browser

Chrome

### Verification

- [X] I have searched for existing issues and confirmed this is not a duplicate
- [X] I have tested this issue with the latest version of Fluxon UI
- [X] I have included all the information needed to reproduce this issue

**Comment by kevinschweikert** [comment]
I'm sorry! After opening this ticket we immediately saw, that the esbuild config includes the deps folder and the issues in our build pipeline were caused by something else!

**Comment by andrielfn** [comment]
Hey @kevinschweikert, thanks for bringing that up. Maybe I can clarify that in the installation guide 💡 At least adding a note or something mentioning this esbuild default config.
