### ISSUE TITLE
Inconsistent border for select active state

### ISSUE THREAD

**Issue by egze** [fluxonui/fluxon#7]
### Fluxon UI Version

1.0.10

### Phoenix LiveView Version

1.0.1

### Current Behavior

When the inputs are active - they get a blue border.

This works for a native select:

<img width="427" alt="SCR-20241219-iogw" src="https://github.com/user-attachments/assets/cc502868-bbf2-47a6-a827-2d33f172f872" />

But the non-native select doesn't get a border:

<img width="323" alt="SCR-20241219-inho" src="https://github.com/user-attachments/assets/1bed8891-e1a5-4d67-baec-7e9c3dbefdd1" />

### Expected Behavior

All active inputs should get a border.

### Browser

Safari

### Verification

- [X] I have searched for existing issues and confirmed this is not a duplicate
- [X] I have tested this issue with the latest version of Fluxon UI
- [X] I have included all the information needed to reproduce this issue

**Comment by andrielfn** [comment]
Another good catch, @egze. Honestly, this one was already on my to-do list, but now it has become a priority 😄

I think I got something working. I will also batch it for the next release.

https://github.com/user-attachments/assets/45e7a62b-7687-4636-bf50-6cc51b5d40c9

**Comment by andrielfn** [comment]
**v.1.0.11** has been released with the fix! I'm closing the issue now. Please reach out if you continue to experience it.
