### ISSUE TITLE
datetime-local input styling is strange

### ISSUE THREAD

**Issue by egze** [fluxonui/fluxon#8]
### Fluxon UI Version

1.0.10

### Phoenix LiveView Version

1.0.1

### Current Behavior

The placeholder for datetime is not centered and too small. (I think it's same also for date input)

<img width="325" alt="image" src="https://github.com/user-attachments/assets/4099d531-1713-4ec8-a863-562a8130d599" />

### Expected Behavior

Should have a better default styling.

### Browser

Safari

### Verification

- [X] I have searched for existing issues and confirmed this is not a duplicate
- [X] I have tested this issue with the latest version of Fluxon UI
- [X] I have included all the information needed to reproduce this issue

**Comment by egze** [comment]
Probably related to different heights. (but I'm not setting the height)

<img width="261" alt="SCR-20241219-iswq" src="https://github.com/user-attachments/assets/ec103aac-0421-47cc-bb5c-4d00a8e46784" />

**Comment by andrielfn** [comment]
Good catch, @egze. It seems to be a Safari issue specifically. I have a fix in place already. I plan to tackle a few more issues today and tomorrow and release them all together.

| Before | After |
|--------|-------|
| ![Before](https://github.com/user-attachments/assets/182cdd7e-5719-4115-b864-8c8eb44a509c) | ![After](https://github.com/user-attachments/assets/7873a996-a11a-49d4-8216-715a4a4f67ee) |

**Comment by andrielfn** [comment]
**v.1.0.11** has been released with the fix! I'm closing the issue now. Please reach out if you continue to experience it.
