### ISSUE TITLE
No interactivity on fresh install

### ISSUE THREAD

**Issue by leonqadirie** [fluxonui/fluxon#9]
### Fluxon UI Version

1.0.10

### Phoenix LiveView Version

1.0.1

### Current Behavior

On a fresh install following the setup instructions, any added interactive components remain static.

It is also somewhat hard to read, I guess this is on purpose though and I'm required to style it more.
![CleanShot 2024-12-19 at 16 00 52@2x](https://github.com/user-attachments/assets/cf7d72a7-06d6-49a6-b0b6-4e512245ac1f)

### Reproduction Steps

```hex     <.accordion>
      <.accordion_item>
        <:header>
          What's the refund policy?
        </:header>
        <:panel>
          Our refund policy allows you to request...
        </:panel>
      </.accordion_item>

      <.accordion_item>
        <:header>
          Can I upgrade my license later?
        </:header>
        <:panel>
          Yes, you can upgrade your license at any...
        </:panel>
      </.accordion_item>

      <.accordion_item>
        <:header>
          Do you offer technical support?
        </:header>
        <:panel>
          Yes, we offer technical support via email.
        </:panel>
      </.accordion_item>
    </.accordion>
```

Steps to reproduce:
1. Create a new Phoenix app
2. Follow the setup instructions 
    1. add the Hex Repository
    2. add Fluxon to project dependencies
    3. update the `lib/[app_name]_web.ex` file to include the Fluxon module.
    4. update `assets/tailwind.config.js` to allow TailwindCSS to process the Fluxon component classes.
    5. update the `assets/js/app.js` file to include the Fluxon hooks and the `onBeforeElUpdated` function.
    6. remove conflicting `CoreComponent;'s
3. Fetch everything via `mix deps.get`
4. Add a Fluxon component and a route to a site displaying it
5. Start the server

### Expected Behavior

I'd expect:
1. The accordion (for example) to actually expand on toggle. Pertains any interactive components I tried so far.
2. The component to already be styled for the default light mode

### Browser

Chrome, Safari

### Verification

- [X] I have searched for existing issues and confirmed this is not a duplicate
- [X] I have tested this issue with the latest version of Fluxon UI
- [X] I have included all the information needed to reproduce this issue

**Comment by andrielfn** [comment]
Hey @leonqadirie, my guess is that your system is configured to dark mode, is that correct? It seems it's rendering the dark mode styles. As it's a brand new app, I believe the issue is that Phoenix defines the `bg-white` in the `body` class, and the component is rendering dark mode, which is causing these hard-to-read colors.

What you could do is set `dark:bg-gray-900` to the body to apply a dark background.

```html
<body class="bg-white dark:bg-gray-900 antialiased">
``` 

This might help as well: https://fluxonui.com/getting-started/installation/troubleshooting#enforcing-light-or-dark-mode

Let me know if that works.

**Comment by leonqadirie** [comment]
Yes, this helps with the styling, thanks! The non-interactivity remains, though.

**Comment by andrielfn** [comment]
Sorry, I missed the non-interactivity part. So, are other components like the dropdown and modal not working either? That makes me think it’s an issue with the Hooks not triggering properly. A couple of questions:

1. Do you see any errors in the browser inspector?
2. Are you rendering the components in a LiveView, or is it a dead view?

**Comment by leonqadirie** [comment]
Nope, none of them are working. 

> 1. Do you see any errors in the browser inspector?

I see:
* ReferenceError: Can't find variable: Hooks ~(fair enough, but removing them and leaving only `...FluxonHooks` doesn't change anything~. Huh, I swear I tried that this afternoon. 
* I seem to have a suspended websocket, never noticed that one. Will investigate.

> 2.Are you rendering the components in a LiveView, or is it a dead view?

Doesn't work in both LiveViews and dead views.

So most probably something around the hooks, or my esbuild may be busted somehow. I never got much into LiveView or even FE so I'm not firm in those aspects.

My `assets/js/app.js` is - stripped by some comments - this:

```js
// Include phoenix_html to handle method=PUT/DELETE in forms and buttons.
import "phoenix_html"
// Establish Phoenix Socket and LiveView configuration.
import {Socket} from "phoenix"
import {LiveSocket} from "phoenix_live_view"
import topbar from "../vendor/topbar"
import { Hooks as FluxonHooks, DOM as FluxonDOM } from 'fluxon';

let csrfToken = document.querySelector("meta[name='csrf-token']").getAttribute("content")
let liveSocket = new LiveSocket("/live", Socket, {
  hooks: {...Hooks, ...FluxonHooks},
  dom: {
    onBeforeElUpdated(from, to) {
      FluxonDOM.onBeforeElUpdated(from, to);
    },
  },
  longPollFallbackMs: 2500,
  params: {_csrf_token: csrfToken}
})

// Show progress bar on live navigation and form submits
topbar.config({barColors: {0: "#29d"}, shadowColor: "rgba(0, 0, 0, .3)"})
window.addEventListener("phx:page-loading-start", _info => topbar.show(300))
window.addEventListener("phx:page-loading-stop", _info => topbar.hide())

// connect if there are any LiveViews on the page
liveSocket.connect()

// expose liveSocket on window for web console debug logs and latency simulation:
// >> liveSocket.enableDebug()
// >> liveSocket.enableLatencySim(1000)  // enabled for duration of browser session
// >> liveSocket.disableLatencySim()
window.liveSocket = liveSocket
```

Other somewhat notable things:
- macOS 15.2
- I'm running nushell (in case I missed some bash scripts)

**Comment by andrielfn** [comment]
What if you change the `hooks:` line to just `hooks: FluxonHooks` (without including the `Hooks`)?

**Comment by leonqadirie** [comment]
I was **very** sure I tried that before... Yes, that seems to solve the issue! Thank you for the swift support! :)

**Comment by andrielfn** [comment]
All good. That actually is an indication that the snippet I am using in the installation guide might not be the best one (which also includes the `...Hooks`). Maybe it's better to just say `hooks: FluxonHooks` and let the users include the other `Hooks` if that's the case.

**Comment by leonqadirie** [comment]
Two additional thoughts from a newbie that set everything up from scratch:
- I was somewhat confused by the guide only marking `FluxonDOM.onBeforeElUpdated(from, to);` as an added line when the whole `dom` key is missing in the `assets/js/app.js` by default.
- The troubleshooting section was missed as it only becomes visible at the upper left corner upon entering the installation guide. I guess an extra sentence at the installation guide's end that links to it might be beneficial.

Thanks for this resource!

**Comment by andrielfn** [comment]
Awesome feedback 🙌 I made a few tweaks to the installation guide. I hope it's a bit better now.

<img width="750" alt="image" src="https://github.com/user-attachments/assets/66f3fdf2-1246-4e75-b1ed-432c56eb816b" />

**Comment by leonqadirie** [comment]
Yeah, that would have worked better for me.

You are more experienced in gauging the `hooks: FluxonHooks,` part, but I'd assume if someone is experienced enough to have own hooks already, they'd be experienced enough to merge them, so I'd wager this is a sensible default.

Awesome! :)
